### ISSUE TITLE
Approach will fail if INT_MAX items are ever pushed

### ISSUE THREAD

**Issue by vitiral** [daurnimator/fifo.lua#4]
It would be a rare Lua application that does it, but if INT_MAX items were ever pushed (and nearly that many popped) this would start using floating point indexes. These would throw away (round) the +1 you are adding, so I think every index would be the same after a push.

It would take a LONG time to reach this point, but it's still slightly concerning to me. I've been thinking about how to implement a fifo and while I had a similar idea, I don't like leaving time bombs in code :)

**Comment by vitiral** [comment]
The simplest solution is that if head is ever == INT_MAX then you move all the current items to the lower indexes.

**Comment by daurnimator** [comment]
> It would be a rare Lua application that does it, but if INT_MAX items were ever pushed (and nearly that many popped) this would start using floating point indexes.

It would only do so at an index of 2^53. Which I don't think is ever realistically reachable?

**Comment by vitiral** [comment]
1 write per microsecond would be 253 years. And actually, I think it's 2^63-1 so it is MUCH longer.

Probably only matters if the Lua is compiled for 32 bit systems. On THOSE it could very easily wrap for a long-running server.

**Comment by vitiral** [comment]
So you probably use different implementations depending on the system.

I have a similar data structure and will do this for that. Feel free to do your own thing!

**Comment by daurnimator** [comment]
> And actually, I think it's 2^63-1 so it is MUCH longer.

53 bits is the size of a double mantissa.


> Probably only matters if the Lua is compiled for 32 bit systems. On THOSE it could very easily wrap for a long-running server.

For lua 5.0-5.3, they always use doubles.

For lua 5.4 you do indeed have a compile option to change the integer size, but almost no one uses it. It could be worth having some sort of feature detection and swap to using floats, but the performance would probably decrease? Either way you're already in a niche of a niche

**Comment by vitiral** [comment]
Yup, totally legit to not worry about it here, sorry for bringing it up, my bad!
